docs: update docs to mention grafana helm chart
grafana/grafana-image-renderer pull request #185
Opened 2020-10-14 13:50 UTC by GabrielCastro

2020-10-14 13:58 UTC, aknuds1 requested changes
Just leaving suggestions for language fixes I spotted. 

@marefr Do you know if it makes sense for us to mention the Helm chart? Do we even support Helm?

2020-10-14 13:58 UTC, aknuds1 commented on README.md
> +The grafana [helm chart](https://github.com/grafana/helm-charts/tree/main/charts/grafana) supports creating a remote renderer by setting `imageRenderer.enabled = true` settings are configured in the
```suggestion
The Grafana [Helm chart](https://github.com/grafana/helm-charts/tree/main/charts/grafana) supports creating a remote renderer by setting `imageRenderer.enabled = true`. Settings are configured in the same way as [remote rendering using Docker](https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md).
```

2020-10-14 13:58 UTC, aknuds1 commented on README.md
> +### Remote Rendering in Kubernetes
We use sentence case in [titles](https://github.com/grafana/grafana/blob/master/contribute/style-guides/documentation-style-guide.md#headings).
```suggestion
### Remote rendering in Kubernetes
```

2020-10-14 13:58 UTC, aknuds1 commented on docs/remote_rendering_using_docker.md
> +## Enable in grafana helm chart
```suggestion
## Enable in Grafana Helm chart
```

2020-10-14 13:58 UTC, aknuds1 commented on docs/remote_rendering_using_docker.md
> +The [helm chart](https://github.com/grafana/helm-charts/tree/main/charts/grafana#image-renderer-plug-in) supports directly enabling a remote image renderer deployment.
```suggestion
The [Helm chart](https://github.com/grafana/helm-charts/tree/main/charts/grafana#image-renderer-plug-in) supports directly enabling a remote image renderer deployment.
```

2020-10-15 13:35 UTC, GabrielCastro commented
It's supported here: https://github.com/grafana/helm-charts/tree/main/charts/grafana

2020-11-04 19:01 UTC, aknuds1 commented
Thanks very much for the PR, but we are sorry to inform you that we've decided to close it, since we think Helm specific information is better placed in the Helm chart documentation itself. We don't provide Helm support as part of this repo.

2020-11-04 19:01 UTC, closed without merging